name: Auto Package Helper
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-py39:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Install Python lib
        run: |
          pip install -r requirements.txt
          
      - name: Init config.json
        run: |
          python config_initer.py
          
      - name: Get version
        run: echo "version=$(cat version.txt)" >> $env:GITHUB_ENV
        
      - name: Package to exe
        run: pyinstaller -w .\main.spec
        
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: genshin-gacha-export_${{ env.version }}
          path: dist

  build-py37:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Install Python lib
        run: |
          pip install -r requirements.txt
          
      - name: Init config.json
        run: |
          python config_initer.py
          
      - name: Get version
        run: echo "version=$(cat version.txt)" >> $env:GITHUB_ENV
          
      - name: Package to exe
        run: pyinstaller -w .\main.spec
        
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: genshin-gacha-export-win7_${{ env.version }}
          path: dist
